version: 1.0.0
routesMap:
  block:
      description: orchestrazione test
      steps : 
            - position : 1
              route : process1
            - position : 2
              route : process2
                          